"""add_missing_user_columns

Revision ID: 309e44c6c0e9
Revises: b23c45d67890
Create Date: 2025-12-17 12:22:59.488365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '309e44c6c0e9'
down_revision: Union[str, Sequence[str], None] = 'b23c45d67890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('position', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('hire_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('employee_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('manager_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('position_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('address', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'users', ['employee_id'])
    op.create_foreign_key(None, 'users', 'positions', ['position_id'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'address')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'position_id')
    op.drop_column('users', 'manager_id')
    op.drop_column('users', 'employee_id')
    op.drop_column('users', 'hire_date')
    op.drop_column('users', 'position')
    op.drop_column('users', 'department')
    # ### end Alembic commands ###
