"""Add raw_status field to AttendanceLog

Revision ID: 50dc6cf92fad
Revises: 309e44c6c0e9
Create Date: 2025-12-17 15:40:06.765009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50dc6cf92fad'
down_revision: Union[str, Sequence[str], None] = '309e44c6c0e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendance_logs_employee_id', table_name='attendance_logs')
    op.drop_index('ix_attendance_logs_id', table_name='attendance_logs')
    op.drop_index('ix_attendance_logs_timestamp', table_name='attendance_logs')
    op.drop_table('attendance_logs')
    op.drop_index('ix_zk_devices_id', table_name='zk_devices')
    op.drop_index('ix_zk_devices_name', table_name='zk_devices')
    op.drop_table('zk_devices')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zk_devices',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('zk_devices_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_sync', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='zk_devices_pkey'),
    sa.UniqueConstraint('ip_address', name='zk_devices_ip_address_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_zk_devices_name', 'zk_devices', ['name'], unique=False)
    op.create_index('ix_zk_devices_id', 'zk_devices', ['id'], unique=False)
    op.create_table('attendance_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verification_mode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['zk_devices.id'], name='attendance_logs_device_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='attendance_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='attendance_logs_pkey')
    )
    op.create_index('ix_attendance_logs_timestamp', 'attendance_logs', ['timestamp'], unique=False)
    op.create_index('ix_attendance_logs_id', 'attendance_logs', ['id'], unique=False)
    op.create_index('ix_attendance_logs_employee_id', 'attendance_logs', ['employee_id'], unique=False)
    # ### end Alembic commands ###
