"""add_shipment_date_range_columns

Revision ID: baffcb53089f
Revises: 473352c06ccd
Create Date: 2026-01-26 08:43:16.951944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baffcb53089f'
down_revision: Union[str, Sequence[str], None] = '473352c06ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('shipment_date_start', sa.Date(), nullable=True))
    op.add_column('contracts', sa.Column('shipment_date_end', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'shipment_date_end')
    op.drop_column('contracts', 'shipment_date_start')
    # ### end Alembic commands ###
